In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = [180,170,170,175,181,175,177,185,179,160]
y = [95,70,60,79,60,63,83,80,75,50]
x,y,len(x),len(y)

([180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
 [95, 70, 60, 79, 60, 63, 83, 80, 75, 50],
 10,
 10)

In [3]:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html
z = np.stack((x,y), axis=0)
z

array([[180, 170, 170, 175, 181, 175, 177, 185, 179, 160],
       [ 95,  70,  60,  79,  60,  63,  83,  80,  75,  50]])

In [4]:
sigma = np.cov(z)
sigma

array([[ 50.62222222,  62.        ],
       [ 62.        , 180.72222222]])

In [8]:
def generateData():
    x=[180,170,170,175,181,175,177,185,179,160]
    y=[95,70,60,79,60,63,83,80,75,50]
    z=np.stack((x, y), axis=0)
    return z

In [9]:
def getCovMatrix(z):
    sigma = np.cov(z)
    return sigma

In [10]:
data1 = generateData()
getCovMatrix(data1)

array([[ 50.62222222,  62.        ],
       [ 62.        , 180.72222222]])

In [15]:
def multivariateNormal(x, d, mean, covariance):
    x_m = x - mean
    return (1. / (np.sqrt((2 * np.pi)**d * np.linalg.det(covariance))) * 
            np.exp(-(np.linalg.solve(covariance, x_m).T.dot(x_m)) / 2))

In [16]:
data2 = generateData()
np.mean(data2[0,:]), np.mean(data2[1,:]) #ilk olan x'in(boy) ortalaması, ikincisi y'nin(kilo) ortalaması

(175.2, 71.5)

In [17]:
x_1 = [175, 72] #Ortalamaları tutuyoruz
d_1 = 2
data3 = generateData()
mean1 = np.array([np.mean(data2[0,:]), np.mean(data2[1,:])]) #boyların ve kiloların ortalaması
covariance1 = getCovMatrix(data3)
multivariateNormal(x_1, d_1, mean1, covariance1)

0.002178581612789265

In [18]:
for i in range(10):
    v = 167+i
    x_1 = [v, 72]
    s = multivariateNormal(x_1, d_1, mean1, covariance1)
    print(v, " ", s)

167   0.0006617920579089793
168   0.0008653451053442351
169   0.0010936064403862028
170   0.001335785435578412
171   0.0015769440170517839
172   0.0017992842345717487
173   0.001984208019848439
174   0.002114845053089614
175   0.002178581612789265
176   0.002169067369696109
